name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup
      run: brew install capnp multimarkdown ninja ragel
    - name: Configure
      run: ./configure
    - name: Build
      run: ninja TextMate
